variables:
  S3_BUCKET_NAME: bdd-reports-test

stages:
  - bdd_test

bdd_test:
  stage: bdd_test
  image: python:3.11.4  # Base image with Python 3.11.4
  script:
    - pwd
    - pip install -r requirements.txt # Install additional dependencies
    - export TEST_TIMESTAMP=$(date "+%Y%m%d_%H%M%S")
    - behave --no-capture -D environment=dev -o reports/scenario_reports.txt | tee reports/outputfile_${TEST_TIMESTAMP}.txt
    - pwd
    - aws s3 cp reports/outputfile_${TEST_TIMESTAMP}.txt s3://${S3_BUCKET_NAME}/Dev/$(date +%Y)/$(date +%m)/$(date +%d)/${TEST_TIMESTAMP}/
  artifacts:
    paths:
      - reports


